### ISSUE TITLE
ACTIVIDAD 1

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-1-mapa-mental-SandyMarissaGs#1]
![INVESTIGACION DOCUMENTAL 1](https://user-images.githubusercontent.com/112224739/187827270-e964559b-9588-4c08-b838-33642431eaac.png)

GRUPO 1BS
SANDY MARISSA GARCIA SANTIAGO.
ACTIVIDAD 1

**Comment by SandyMarissaGs** [comment]
![Uploading INVESTIGACION DOCUMENTAL 1.png…]()
Actividad 1. 
Sandy Marissa García Santiago.
Grupo 1BS

**Comment by SandyMarissaGs** [comment]
![Uploading INVESTIGACION DOCUMENTAL 1.png…]()
Sandy Marissa García Santiago.
Grupo 1BS.
Actividad 1

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 1 MAPA MENTAL
DE 20% DE LA ACTIVIDAD OBTUVISTE 17.6% DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
